title: Intro sok (edit _config.yml)

description: > # this means to ignore newlines until "contact:"
  Will be brilliant.

contact:
  email: derek.clark@uit.no
  name: Derek J. Clark (edit _config.yml)

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
