title: Intro sok 

description: Will be brilliant
  

contact:
  email: derek.clark@uit.no
  name: Derek J. Clark (edit _config.yml)

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
