title: SOK-yyyy Introduction to economics 

description: 
  Will be brilliant
  

contact:
  email: derek.clark@uit.no
  name: Derek J. Clark 

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
